# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlayconsoleCli < Formula
  desc "Fast, lightweight, and scriptable CLI for Google Play Console"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.0/playconsole-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "6c1b1a3cd24cab4004a37626a1368d94ac38019191ea42d6176d3763a123a5f7"

      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.0/playconsole-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "6bbcd2b6904056be0246413edc14988c3ff8ed2f84c9e37cf27048e4edafdabc"

      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.0/playconsole-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "9b9ca3edc76f9ec6474b73929e8eebda8dc84fe2ae5d640c755e7b09fbb6b60e"
      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.0/playconsole-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "03bccff708d994fce6c2f1c080c78331a397b8e9618bb9a53837971fc8633ad0"
      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
