# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlayconsoleCli < Formula
  desc "Fast, lightweight, and scriptable CLI for Google Play Console"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.1/playconsole-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "c18d5b216a348c1044b8c91c2125e87f8d6c4eb2e9f685407e55122aa4ac51e4"

      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.1/playconsole-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "6087be85be7ad431ca956da7b6051f81e377aa7a950da5bc179dc0f8a98d33da"

      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.1/playconsole-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "94e272ccc7167cff25f9295fc71243fc4ea8dc05396a80964176bebb6d66e04f"
      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.1/playconsole-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "04c021825f7cbb72b68737c95bcc7f429795896e2841b8d0668f31491d67972c"
      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
