# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlayconsoleCli < Formula
  desc "Fast, lightweight, and scriptable CLI for Google Play Console"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.0/playconsole-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "0a39f3b81185f8562a053bf0d691d843a2b048b65993c145b2d2e53969f887ab"

      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.0/playconsole-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "ca237c22b741012b1333590ac8cd93a7bfe5b4319a9881c883bc9d24efaeecae"

      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.0/playconsole-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "00be381619b19129235a5187d6c7315fefb63020309a8de40927fa519ccfdf21"
      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.4.0/playconsole-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "1a646630dbf636521f78842c0f17bddfda9a20dc6b32dcc30a912460f92f0601"
      define_method(:install) do
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
