# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RevenuecatCli < Formula
  desc "Fast, lightweight, and scriptable CLI for RevenueCat"
  homepage "https://github.com/AndroidPoet/revenuecat-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.1.0/revenuecat-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "daa3b330ad7b717dba22b0910d738a56e1f19e5eff4517e31f7da4b7be2475b9"

      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.1.0/revenuecat-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a6201b137918ee1b0eae34ab168bc993e5505d4626bdcc5a4539f56025221681"

      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.1.0/revenuecat-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "d957b50d0ac95a8629b2361943346031114eeee9761c1d6e6350bc0052534b34"
      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.1.0/revenuecat-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "75bf9017a46bb2af9ddd8ccaabab58b26a62bb92e84778636110b770c132bb52"
      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
  end

  test do
    system "#{bin}/rc", "version"
  end
end
