# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Alias for playconsole-cli"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.5.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.10/playconsole-cli_0.5.10_darwin_amd64.tar.gz"
      sha256 "93241219ee2e832bf58500dedd0f481d12aaf39f3098ea334b329dbf7e80005c"

      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.10/playconsole-cli_0.5.10_darwin_arm64.tar.gz"
      sha256 "dce4d17a61270397e5385c3e368e4397e3a3e75335cd9920bcf48b74e53f939f"

      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.10/playconsole-cli_0.5.10_linux_amd64.tar.gz"
      sha256 "f27b1ea8da6b75db1a79ed9253e55632af651e3994e9f4374cbf02d3e10580d5"
      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.10/playconsole-cli_0.5.10_linux_arm64.tar.gz"
      sha256 "c3ce21d2a3b0bd0f5ad024acda95906ad96fb5c2fd3df44735d2972ed85e4ef2"
      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
