# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Alias for playconsole-cli"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.5.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.13/playconsole-cli_0.5.13_darwin_amd64.tar.gz"
      sha256 "adde624748ea8ef738a26da29c22bdf27f34b782900a898060b0bc60dd48a952"

      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.13/playconsole-cli_0.5.13_darwin_arm64.tar.gz"
      sha256 "33698f3b6916c0e58269736fdc866da06b707a4a3f570e6a61b3dc4c69d7ca6e"

      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.13/playconsole-cli_0.5.13_linux_amd64.tar.gz"
      sha256 "18acadf73e33a71913d9335b92dc1b93cb4093b05fdad494521d6b4ed99dd794"
      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.13/playconsole-cli_0.5.13_linux_arm64.tar.gz"
      sha256 "134211ac0dba88c91dcd29925f2643af5854af2de76470df6d2b7dcca6470888"
      def install
        bin.install "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
