# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlayconsoleCli < Formula
  desc "Fast, lightweight, and scriptable CLI for Google Play Console"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.5.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.7/playconsole-cli_0.5.7_darwin_amd64.tar.gz"
      sha256 "ce2aab38b3ef0397c6d0df94b47c3fc7aa056b79e4755403efb3afac4b10714f"

      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.7/playconsole-cli_0.5.7_darwin_arm64.tar.gz"
      sha256 "b8112964435236a1ff5847165472ceedf05037d2f2315862926d065513076095"

      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.7/playconsole-cli_0.5.7_linux_amd64.tar.gz"
      sha256 "a43e5fd5a6ff9afb74547a81c6fbb7c563a7abba3b5959c4998068eb52410f9a"
      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.7/playconsole-cli_0.5.7_linux_arm64.tar.gz"
      sha256 "decd6f0a09948404364ac95e090837a3c63c1312a10eb02e45c545b94c95cf9d"
      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
