# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlayconsoleCli < Formula
  desc "Fast, lightweight, and scriptable CLI for Google Play Console"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.5.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.12/playconsole-cli_0.5.12_darwin_amd64.tar.gz"
      sha256 "28e7c686e03f8e942ef1258a5acd968e673e87cd3304694ea9c40e5edd170b59"

      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.12/playconsole-cli_0.5.12_darwin_arm64.tar.gz"
      sha256 "623d1914d92f1d0fa6662703e50ed6ad7d95fe7d769fa769c1dfbfc77a112a50"

      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.12/playconsole-cli_0.5.12_linux_amd64.tar.gz"
      sha256 "ada5bed7204192bbdc23ad61ab3a48c18cbeb86fb85a0e471b49fa464a4411c8"
      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.12/playconsole-cli_0.5.12_linux_arm64.tar.gz"
      sha256 "4cb6f1d68bd89be786e35963b42b946623352abcec840ac79ff59ef22bcbdd1f"
      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
