# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlayconsoleCli < Formula
  desc "Fast, lightweight, and scriptable CLI for Google Play Console"
  homepage "https://github.com/AndroidPoet/playconsole-cli"
  version "0.5.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.11/playconsole-cli_0.5.11_darwin_amd64.tar.gz"
      sha256 "7e75d846fc4f556dde88cddec6a88a8e259f4ff7d1e107973a88319abe5a65e8"

      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.11/playconsole-cli_0.5.11_darwin_arm64.tar.gz"
      sha256 "8d9165de208ef56a7d92811a4357f1fd102478a764d53ddd35d3636c2f2d72c5"

      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.11/playconsole-cli_0.5.11_linux_amd64.tar.gz"
      sha256 "959131a195f53c3f6dcfe8db06d7d9b1ee5de209d9ab86ccae739d1d50554af2"
      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/playconsole-cli/releases/download/v0.5.11/playconsole-cli_0.5.11_linux_arm64.tar.gz"
      sha256 "c8295b5499f30afaa50caff884c783a6801ff9cf14982d0937420dfa2adeb3b6"
      def install
        bin.install "playconsole-cli"
        bin.install_symlink "playconsole-cli" => "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
