# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RevenuecatCli < Formula
  desc "Fast, lightweight, and scriptable CLI for RevenueCat"
  homepage "https://github.com/AndroidPoet/revenuecat-cli"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.4.2/revenuecat-cli_0.4.2_darwin_amd64.tar.gz"
      sha256 "7d95eb27c428ce54662adf0fb00da4ca6be3adbd5602504268b829e4121958bc"

      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.4.2/revenuecat-cli_0.4.2_darwin_arm64.tar.gz"
      sha256 "789287d6169973805619a8b7ac7ae2eec479f3849fd1f0fc2580eec388f7568e"

      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.4.2/revenuecat-cli_0.4.2_linux_amd64.tar.gz"
      sha256 "13b6ceda892cc13f421f7b85fdee82a3f402e599d1910dbb909088407439c831"
      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.4.2/revenuecat-cli_0.4.2_linux_arm64.tar.gz"
      sha256 "e3f1bacb8dd03c091be50a8b6017bcc47f18d0a4fb9ac6a3ab0d2e695616aa42"
      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
  end

  test do
    system "#{bin}/rc", "version"
  end
end
