# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RevenuecatCli < Formula
  desc "Fast, lightweight, and scriptable CLI for RevenueCat"
  homepage "https://github.com/AndroidPoet/revenuecat-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.2.0/revenuecat-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "39d13d6a76d3822b1ac38b8c67e6ef14855012afe8ca465bfbf68ee9fefc6df2"

      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.2.0/revenuecat-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "579fac8d37cb511c3ba4ab578118f5579ec616178afc09d5cff993165d71e91a"

      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.2.0/revenuecat-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "d5f9d731522ff502ca38b4fecf2c92922a789be6d692d980a75d2fc5bc9406e3"
      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndroidPoet/revenuecat-cli/releases/download/v0.2.0/revenuecat-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "2513f2ee06e0da56b64cff8edf057c3042a1c1cc19aef71940d40e34b58b522f"
      define_method(:install) do
        bin.install "revenuecat-cli"
        bin.install_symlink "revenuecat-cli" => "rc"
      end
    end
  end

  test do
    system "#{bin}/rc", "version"
  end
end
